# Generated by Django 3.0 on 2019-12-22 13:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chairs',
            fields=[
                ('chair_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('is_real', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('room_row', models.IntegerField()),
                ('room_col', models.IntegerField()),
                ('availble_number', models.IntegerField(default=0)),
                ('total_seat', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('major', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=128)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('rent_id', models.IntegerField(default=2, primary_key=True, serialize=False)),
                ('begin_time', models.DateTimeField(default=datetime.datetime(2019, 12, 22, 13, 28, 1, 315159, tzinfo=utc))),
                ('arrive_time', models.DateTimeField(default=datetime.datetime(2019, 12, 22, 13, 28, 1, 315159, tzinfo=utc))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2019, 12, 23, 13, 28, 1, 315159, tzinfo=utc))),
                ('chair', models.ForeignKey(db_column='chair', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.Chairs')),
                ('student', models.ForeignKey(db_column='student', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.Students')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student0', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='out', to='data.Students')),
                ('student1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.Students')),
            ],
        ),
        migrations.AddField(
            model_name='chairs',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Rooms'),
        ),
    ]
