# Generated by Django 3.0 on 2019-12-17 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student0', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='out', to='data.Students')),
                ('student1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.Students')),
            ],
        ),
    ]
