# Generated by Django 3.0 on 2019-12-21 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('begin_time', models.DateTimeField()),
                ('chair', models.OneToOneField(db_column='chair', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='data.Chairs')),
                ('arrive_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.OneToOneField(db_column='student', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.Students')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student0', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='out', to='data.Students')),
                ('student1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.Students')),
            ],
        ),
    ]
