# Generated by Django 3.0 on 2019-12-21 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_friends_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('room_row', models.IntegerField()),
                ('room_col', models.IntegerField()),
                ('availble_number', models.IntegerField()),
                ('chairs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Chairs')),
            ],
        ),
    ]
