# Generated by Django 3.0 on 2019-12-21 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20191221_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='chairs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Chairs'),
        ),
    ]
