# Generated by Django 3.0 on 2019-12-21 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20191221_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='chairs',
        ),
        migrations.AddField(
            model_name='chairs',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Rooms'),
        ),
    ]
