# Generated by Django 3.0 on 2019-12-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20191221_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairs',
            name='chair_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
