# Generated by Django 3.0 on 2019-12-27 13:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20191227_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='student0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out', to='data.Students'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='student1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Students'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='arrive_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 13, 57, 49, 307510, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='begin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 13, 57, 49, 307510, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 28, 13, 57, 49, 307510, tzinfo=utc)),
        ),
    ]
