# Generated by Django 3.0 on 2019-12-27 14:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20191227_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='close_attention',
            new_name='close',
        ),
        migrations.AlterField(
            model_name='rent',
            name='arrive_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 14, 47, 46, 776452, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='begin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 14, 47, 46, 776452, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 28, 14, 47, 46, 776452, tzinfo=utc)),
        ),
    ]
